name: Update Documentation

on:
  push:
    branches:
      - main
      
jobs:
  build:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move README.md to docs
        run: |
          for dir in $(find . -type d); do
              if ! grep -Fxq "$dir" .gitignore && [ -f "$dir/README.md" ] && [[ $dir != *"/docs"* ]]; then
                  newdir=$(echo "$dir" | sed "s/\./\.\/docs/")
                  if [ ! -d "$newdir" ]; then
                      mkdir -p "$newdir"
                  fi
                  cp "$dir/README.md" "$newdir/index.md"
              fi
          done

      - name: Build and deploy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m '[Bot] Update Docs'
            git push
          else
            echo "No changes to commit"
          fi
