name: Update GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  build:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Build Jekyll site
        run: | 
          gem install bundler jekyll
          bundle install
          bundle exec jekyll build -d docs

      - name: Convert README.md to index.html
      - uses: docker://pandoc/core:2.9
        run: |
          for dir in $(find . -type d); do
            if [ -f "$dir/README.md" ]; then
              pandoc "$dir/README.md" -o "$dir/index.html"
            fi
          done

      - name: Build and deploy
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m '[Bot] Update Docs'
          git push
